### ISSUE TITLE
How to decompress lzjs in python?

### ISSUE THREAD

**Issue by gerardcsaperas** [polygonplanet/lzjs#1]
Hey!

First of all, great tool. Thank you so much for putting it out.

However, I am using it to compress the cookies we send through the server (they are huge due to business rules and considerations), and my customers use a variety of programming languages to handle cookies.

I've been looking for a way to, for example, **decompress an lzjs compressed string in Python**. Would that be possible?

Thank you in advance.

Kind Regards,

Gerard

**Comment by polygonplanet** [comment]
@gerardcsaperas
Sorry for the very late comment... lzjs is based on an original algorithm, and so far, it has only been implemented in this repository (JavaScript version). Porting to Python is not easy for me, but welcome if anyone is able to implement!
