### ISSUE TITLE
How to decompress data in dart/flutter

### ISSUE THREAD

**Issue by CYL0728** [polygonplanet/lzjs#2]
Hi developer,

my backend using lzjs library compress data and send data to flutter app. In flutter app, i'm using another LZ algorithm library to decompress it, but the decompress data is not correct. 
![image](https://github.com/polygonplanet/lzjs/assets/94677785/f9726b0c-9838-4a82-8e53-cb30aef5c6fe)

May i know how to decompress data in flutter or can  request have a lzjs library in dart version?

Thanks

**Comment by polygonplanet** [comment]
@CYL0728 
Data compressed by the lzjs library must be decompressed by lzjs itself. This is because lzjs is the original compression algorithm.
There is currently no dart version of lzjs... (Pull requests are welcome!)

```javascript
const decompressedData = lzjs.decompress(compressedData);
```
